import Head from "next/head";
import { useContext } from "react";
import { useRouter } from "next/router";
import { context } from "../reducer/index";

export default function Home() {
  let [store] = useContext(context);
  const router = useRouter();

  console.log("store", store);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>count: {store.count}</div>
      <div onClick={() => router.push("/")}>back to home</div>
    </div>
  );
}
